# Используем Python-образ
FROM python:3.8
ENV DEBIAN_FRONTEND noninteractive
ENV PATH="${PATH}:/opt/cprocsp/bin/amd64/"
ENV PYTHONPATH "${PYTHONPATH}:/app/pycades"
RUN apt-get update 
RUN apt-get install -y wget cmake build-essential libboost-all-dev python3-dev unzip
# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY [ "requirements-test.txt", "pycades.zip", "linux-amd64_deb.tgz", "./"]

RUN tar zxvf linux-amd64_deb.tgz 
RUN chmod +x /app/*.*
RUN  /app/linux-amd64_deb/install.sh
RUN  apt -o Apt::Get::Assume-Yes=true install /app/linux-amd64_deb/lsb-cprocsp-devel_5.0*.deb && \ 
    apt -o Apt::Get::Assume-Yes=true install  /app/linux-amd64_deb/lsb-cprocsp-base_5.0*.deb && \ 
    apt -o Apt::Get::Assume-Yes=true install  /app/linux-amd64_deb/cprocsp-pki-cades*.deb
RUN unzip pycades.zip 
RUN cd pycades && \
    mkdir build && \
    cd build && \ 
    cmake .. && \
    make -j4 && \
    chmod +x /app/pycades/build/pycades.so && \
    cp /app/pycades/build/pycades.so /usr/local/lib
RUN rm /app/linux-amd64_deb.tgz /app/pycades.zip 
RUN set -ex 
# Устанавливаем зависимости
RUN pip install -U pip
RUN pip install -r requirements-test.txt
COPY ./xml /xml
COPY  ./app.py ./test_app.py ./pytest.ini /app/ 
COPY ./certs /certs
COPY ./xxx.000 /var/opt/cprocsp/keys/root/xxx.000
# Запускаем тесты при запуске контейнера
ENTRYPOINT [ "sh", "/certs/entrypoint test.sh" ]
